### ISSUE TITLE
Can't find the package "@commerce/shared": "1.0.0"  during npm install

### ISSUE THREAD

**Issue by shamim-42** [secmohammed/microservices-e-commerce-nest-api#5]
This is a fantastic project for the microservice enthusiasts !
Unfortunately I can't run the `gateway` microservice. In fact, I can't even install the packages via npm. `@commerce/shared` package is not found.

Can you fix this ?

**Comment by secmohammed** [comment]
Hello @shamim-42 ! you can't actually install @commerce/shared from npm, as It's a local package.
the shared module is named @commerce/shared at its package.json, kindly search for how to install local packages.

**Comment by shamim-42** [comment]
Thank you brother Mohammed Osama ! Now it is working.
If you have a little documentation then it would better to understand.
Anyway your codes are well structured.
@secmohammed

**Comment by shamim-42** [comment]
Thank you brother. Now your code is working.

**Comment by secmohammed** [comment]
unfortunately, I don't have a docs for the project, but if there is any question or something isn't clear. Feel free to open an issue.
